### PR TITLE
sbt mutation testing

### PR DESCRIPTION
**Pull request by willis7**
Add un-configured `sbt mutationTest` task. Adds a quality metric to unit tests by injecting
mutations (bugs) and validating how many are killed.

To test:

`$ sbt mutationTest` and a report can be found in the `target` folder.

This is open for discussion more than a well thought out PR. I've seen improved tests from introducing this in the past, and it can make testing fun (think space invaders for tests!). The report says none of the mutations were killed, which I find hard to believe, but then I haven't configured the plugin; it may not be running against the correct source sets (unit/integ). We may also wish to fine tune the mutations we want to introduce, along with adding some exclusions i.e. don't test controllers (assuming the logic has been extracted).

Keen to get your thoughts; is this a load of rubbish, or something worth investing in?  The 1 line of code change wasn't taxing, so I'm happy if we choose not to progress (with a valid reason ofc ;-) ).

### CODE REVIEW

**Comment by willis7** [comment]
I did some digging an it looks like the plugin is still early development; https://github.com/sugakandrey/scalamu/issues/1

I forgot that I had also used an older version of the plugin as the latest failed, but that could be down to the rubbish wifi in my airbnb. I will try again with the latest and report back

**Comment by willis7** [comment]
Ok, so the latest version they recommend in the README (0.1.2) doesn't resolve, but I was able to bump 0.1.0 -> 0.1.1. The effect is that 5 mutations get killed now, including the one we discussed today @nigelhp , so that looks a little better.  I guess the question now becomes; is it useful in its current state? It's clearly not massively stable, but may be adding value.

The configuration could still be optimised to exclude generated code.

**Comment by nigelhp** [comment]
This is of interest, and I guess ultimately, it cannot really harm to add this to the build.

In its current state however, I'm still not really sure what the output is telling us.  Some of the issues flagged with the new code that I would consider to be the most serious, are issues that I cannot replicate myself.  i.e. if I change the code in the way that the mutation description suggests it has, the tests correctly fail.  It therefore feels as if "buy in" to further manual investigation is going to be required.

Another point to note, and one I have mentioned a couple of times, is that the team has no build monitors / dashboards.  I think this needs to be considered, as I don't see developers consistently running all of the various plugin reports such as checkstyle / mutation testing locally.  And if they are just being run on the build servers, and no one is actually looking at the output, then ultimately we're just fooling ourselves.  Without a simple "trend dashboard" that is blatantly visible to everyone and ultimately encourages someone to jump in and try to pick off some issues, my experience is that the reports will ultimately be ignored.

If we cannot get some build monitors, perhaps we need a "post standup" session on a regular basis, where we use the TV to go through some of the reports.  This is definitely not the preferred approach however...

If we do proceed with this, we should exclude the Play auto-generated code.

**Comment by willis7** [comment]
Good points, and I agree. I posted a page on Confluence about how to enable `pre-commit` hooks. I think that would enforce checks before a push - but, it's an opt-in option, developers have to want to enable it.

I think some of the things you raise would be good topics for the retro.

Lets keep this PR open for now and keep rebasing. It will be useful to see if it adds value over time. In the meantime I will tune the config to make it more bearable.

**Pull request closed without merging**
